%%% project: morgen - Model Order Reduction for Gas and Energy Networks
%%% version: 0.9 (2020-11-24)
%%% authors: C. Himpe (0000-0003-2194-6754), S. Grundel (0000-0002-0209-6566)
%%% license: BSD 2-Clause (opensource.org/licenses/BSD-2-clause)
%%% summary: Pipeline from PSI

for s = {'imex1','imex2','rk4','generic'}
    for m = {'ode_mid','ode_end'}

        morgen('pipeline','training',m{:},s{:},{ ...
                                                 'pod_c', ...
                                                 'ds_co', ...
                                                 'ds_wx', ...
                                                 'ds_wz', ...
                                                 'bt_co', ...
                                                 'bt_wx', ...
                                                 'bt_wz', ...
                                                 'dmd_c', ...
                                                },'notest');

         morgen('pipeline','period',m{:},s{:},{ ...
                                                ['pipeline--',m{:},'--pod_c.rom'], ...
                                                ['pipeline--',m{:},'--ds_co.rom'], ...
                                                ['pipeline--',m{:},'--ds_wx.rom'], ...
                                                ['pipeline--',m{:},'--ds_wz.rom'], ...
                                                ['pipeline--',m{:},'--bt_co.rom'], ...
                                                ['pipeline--',m{:},'--bt_wx.rom'], ...
                                                ['pipeline--',m{:},'--bt_wz.rom'], ...
                                                ['pipeline--',m{:},'--dmd_c.rom'], ...
                                               },'compact');

    end%for
end%for
