%%% project: morgen - Model Order Reduction for Gas and Energy Networks
%%% version: 1.2 (2022-10-07)
%%% authors: C. Himpe (0000-0003-2194-6754), S. Grundel (0000-0002-0209-6566)
%%% license: BSD-2-Clause (opensource.org/licenses/BSD-2-clause)
%%% summary: Test Polish pipeline from Cha09.

morgen('Cha09','training2','ode_end','rk2hyp',{ ...
                                              'pod_r', ...
                                              'gopod_r', ...
                                              'dmd_r', ...
                                              'eds_ro_l', ...
                                              'eds_wx_l', ...
                                              'eds_wz_l' ...
                                             },'dt=10','cfl=0.25','ord=150','notest');

morgen('Cha09','period','ode_end','rk2hyp',{ ...
                                            'Cha09--ode_end--rk2hyp--pod_r.rom', ...
                                            'Cha09--ode_end--rk2hyp--gopod_r.rom', ...
                                            'Cha09--ode_end--rk2hyp--dmd_r.rom', ...
                                            'Cha09--ode_end--rk2hyp--eds_ro_l.rom', ...
                                            'Cha09--ode_end--rk2hyp--eds_wx_l.rom', ...
                                            'Cha09--ode_end--rk2hyp--eds_wz_l.rom', ...
                                           },'dt=10','cfl=0.25','ord=150','ys=-4');

morgen('Cha09','period','ode_end','generic',{},'dt=10','cfl=0.25');

