%%% project: morgen - Model Order Reduction for Gas and Energy Networks
%%% version: 1.2 (2022-10-07)
%%% authors: C. Himpe (0000-0003-2194-6754), S. Grundel (0000-0002-0209-6566)
%%% license: BSD-2-Clause (opensource.org/licenses/BSD-2-clause)
%%% summary: Reduction template

for s = {'imex1','imex2','cnab2'}
    for m = {'ode_mid','ode_end'}
%
        morgen('template_network','training',m{:},s{:},{ ...
                                                        'pod_r', ...
                                                        'eds_ro_l', ...
                                                        'eds_wx_l', ...
                                                        'eds_wz_l', ...
                                                        'bpod_ro_l', ...
                                                        'ebt_ro_l', ...
                                                        'ebt_wx_l', ...
                                                        'ebt_wz_l', ...
                                                        'gopod_r', ...
                                                        'ebg_ro_l', ...
                                                        'ebg_wx_l', ...
                                                        'ebg_wz_l', ...
                                                        'dmd_r', ...
                                                       },'dt=20','ord=150','notest');
%
        morgen('template_network','test',m{:},s{:},{ ...
                                                    ['template_network--',m{:},'--',s{:},'--pod_r.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--eds_ro_l.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--eds_wx_l.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--eds_wz_l.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--bpod_ro_l.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--ebt_ro_l.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--ebt_wx_l.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--ebt_wz_l.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--gopod_r.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--ebg_ro_l.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--ebg_wx_l.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--ebg_wz_l.rom'], ...
                                                    ['template_network--',m{:},'--',s{:},'--dmd_r.rom'], ...
                                                   },'dt=20','ord=150',['pid=',plotid]);
%
    end%for
end%for

