%%% project: morgen - Model Order Reduction for Gas and Energy Networks
%%% version: 1.1 (2021-08-08)
%%% authors: C. Himpe (0000-0003-2194-6754), S. Grundel (0000-0002-0209-6566)
%%% license: BSD-2-Clause (opensource.org/licenses/BSD-2-clause)
%%% summary: Test actual network from LotH67.

%
morgen('LotH67d','training','ode_end','imex1',{ ...
                                               'pod_r', ...
                                               'gopod_r', ...
                                               'dmd_r', ...
                                               'eds_ro_l', ...
                                               'eds_wx_l', ...
                                               'eds_wz_l'
                                              },'dt=20','notest');
%
morgen('LotH67d','day','ode_end','imex1',{ ...
                                          'LotH67d--ode_end--imex1--pod_r.rom', ...
                                          'LotH67d--ode_end--imex1--gopod_r.rom', ...
                                          'LotH67d--ode_end--imex1--dmd_r.rom', ...
                                          'LotH67d--ode_end--imex1--eds_ro_l.rom', ...
                                          'LotH67d--ode_end--imex1--eds_wx_l.rom', ...
                                          'LotH67d--ode_end--imex1--eds_wz_l.rom'
                                         },'dt=20','ys=-9');
%
