%%% project: morgen - Model Order Reduction for Gas and Energy Networks
%%% version: 1.2 (2022-10-07)
%%% authors: C. Himpe (0000-0003-2194-6754), S. Grundel (0000-0002-0209-6566)
%%% license: BSD-2-Clause (opensource.org/licenses/BSD-2-clause)
%%% summary: Test Chinese transport network

morgen('JinW','training','ode_end','imex1',{ ...
                                            'pod_r', ...
                                            'gopod_r', ...
                                            'dmd_r', ...
                                            'eds_ro_l', ...
                                            'eds_wx_l', ...
                                            'eds_wz_l' ...
                                           },'dt=40','ord=250','notest');

morgen('JinW','random','ode_end','imex1',{ ...
                                          'JinW--ode_end--imex1--pod_r.rom', ...
                                          'JinW--ode_end--imex1--gopod_r.rom', ...
                                          'JinW--ode_end--imex1--dmd_r.rom', ...
                                          'JinW--ode_end--imex1--eds_ro_l.rom', ...
                                          'JinW--ode_end--imex1--eds_wx_l.rom', ...
                                          'JinW--ode_end--imex1--eds_wz_l.rom', ...
                                         },'dt=40','ord=250','ys=-3');

