%%% project: morgen - Model Order Reduction for Gas and Energy Networks
%%% version: 0.9 (2020-11-24)
%%% authors: C. Himpe (0000-0003-2194-6754), S. Grundel (0000-0002-0209-6566)
%%% license: BSD 2-Clause (opensource.org/licenses/BSD-2-clause)
%%% summary: Pipeline test for KoMSO Success Stories

morgen('Cha09','training','ode_mid','imex1',{ ...
                                                 'pod_s', ...
                                                 'ds_co_s', ...
                                                 'ds_wx_s', ...
                                                 'ds_wz_s', ...
                                                 'bt_co_s', ...
                                                 'bt_wx_s', ...
                                                 'bt_wz_s', ...
                                                },'notest');

morgen('Cha09','period','ode_mid','imex1',{ ...
                                               'Cha09--ode_mid--pod_s.rom', ...
                                               'Cha09--ode_mid--ds_co_s.rom', ...
                                               'Cha09--ode_mid--ds_wx_s.rom', ...
                                               'Cha09--ode_mid--ds_wz_s.rom', ...
                                               'Cha09--ode_mid--bt_co_s.rom', ...
                                               'Cha09--ode_mid--bt_wx_s.rom', ...
                                               'Cha09--ode_mid--bt_wz_s.rom', ...
                                              });
