function r = cmp_friction(Re,D,k)
%%% project: morgen - Model Order Reduction for Gas and Energy Networks
%%% version: 0.9 (2020-11-24)
%%% authors: C. Himpe (0000-0003-2194-6754), S. Grundel (0000-0002-0209-6566)
%%% license: 2-Clause BSD (opensource.org/licenses/BSD-2-clause)
%%% summary: Compare friction factors

    r = [friction_altshul(Re,D,k); ...
         friction_schifrinson(Re,D,k); ...
         friction_hofer(Re,D,k); ...
         friction_nikuradse(Re,D,k); ...
         friction_pmt1025(Re,D,k); ...
         friction_igt(Re,D,k)];
end

